name: Docker Build and Publish

on:
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUBRUNNERID : $GITHUB_RUN_NUMBER
  IMGNAME: "ckliew/httpapp:$GITHUB_RUN_NUMBER"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      #- name: abc
      #  run: |
      #    echo "ckliew/httpapp:${GITHUB_RUN_NUMBER}"
      #    echo "ckliew/httpapp:${GITHUB_RUN_NUMBER}" > $IMGNAME

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check whether docker is there or not
        run: docker version

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ckliew
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: abc
        run: echo public-${{env.GITHUBRUNNERID}}.zip

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          #tags: ckliew/httpapp:test
          tags: ${{ env.IMGNAME}}
          build-args: |
            IMGNAME: ${{ env.IMGNAME }}
          #tags: "${{env.IMGNAME}}"
